### ISSUE TITLE
On every update new gists are generated

### ISSUE THREAD

**Issue by ghost** [Ventto/bacpac#1]
I'm using the AUR package with pacaur and on every update of the package the old gists are not abandoned and new ones are created. This is really disturbing because I have a lot of unused gists and I lost the version control.

```
:: Pug: fresh install is needed.
==> Authentification on Github...
Obtaining OAuth2 access_token from github.
GitHub username: 

```

**Comment by Ventto** [comment]
Thanks for the feedback. I noticed your comment on the package as well.
Except the Makefile that needs to be fixed, updating *pug* removes all files initially created during the installation process, it means the token file `/root/.gist` (generated after logging) and gists IDs `/etc/pug`.

A solution would be post-installation to backup the above files in order to restore them for the next package update.

Workflow:

* Installing *pug* package for the first time:
 1. The Makefile tries to restore `/etc/pug` from its backup that does not exit.
 1. The Makefile runs `pug.sh`
 1. `pug()` sources `/etc/pug`, if no gist IDs detected so it calls `pug_install()`
 1. `pug_install` causes to login and create gists
 1. Still in the installation process, *pug* is already installed and hooked to package events
 1. *pug* is triggered just after its own installation
 1. `pug()` sources `/etc/pug`, gist IDs are detected so it calls `pug_update()`
 1. `pug_update()` creates backup files blindly.
 1. Finally, it pushs *pug* (as new package) to the AUR gist and quits.

* Updating *pug* package:
 1. All installed files from *pug* package are removed 
 1. The Makefile restores `/etc/pug` from its backup.
 1. The Makefile runs `pug.sh`
 1. `pug()` sources `/etc/pug`, gist IDs are detected so it calls `pug_update()`
 1. `pug_update()` creates backup files blindly (creates a backup of the `/root/.gist` token file).
 1. Still in the updating process, *pug* is already re-installed and hooked to package events
 1. *pug* is triggered just after its own update
 1. [...] and so on

PS: Accordingly, to force a re-installation, these backup files must be deleted.

**Comment by Ventto** [comment]
If token or IDs files are missing, I tried to call `pug_install` directly.
Unfortunately the hook avoids interactive interaction with the *pug* script.

**Comment by Ventto** [comment]
I've squashed all previous changes and pushed a new release v1.2.
Once more, update *pug* with *pacaur* (this time, it'll generate gists and the backup files). 
Afterwards, any update won't cause to add new gists as long as the backup files still remain.
